services:
  db_server:
    image: postgres:15

    container_name: my_test_postgres

    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - LANG=C.UTF-8

    ports: 
    - "5432:5432"
  
    volumes: 
    - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: